server:
  port: 8083
  servlet:
    context-path: /fruithome
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fruithome?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
debug: true
logging:
  file: fruithome.log
  level:
    com.wei.fruithome.dao.user: debug

mybatis:
  type-aliases-package: com.wei.fruithome.dao
  mapper-locations: mapper/*.xml
