server:
  port: 8081
  servlet:
    context-path: /fruithome
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fruithome?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
  jpa:
    show-sql: true
debug: true
logging:
  path: /var/log
  file: fruithome.log
  level:
    com.wei.fruithome.dao: debug

