server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fruithome?characterEncoding=utf8&useSSL=true
    username: root
    password: root
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource


