server:
  port: 8083
  servlet:
    context-path: /fruithome
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fruithome
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    maxActive: 200
    initialSize: 2
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

