server:
  port: 8083
  servlet:
    context-path: /fruithome
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fruithome?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
